apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-data
  labels:
    app: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
