apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-db-data
  labels:
    app: matomo-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
