---
resources:
  #- ./manifests/lette-web-ingress.yaml # replaced by gateway api
  - ./manifests/lette-web-routes.yaml
  - ./manifests/lette-console-deployment.yaml
  - ./manifests/lette-console-service.yaml
  - ./manifests/lette-landingpage-deployment.yaml
  - ./manifests/lette-landingpage-service.yaml

generators:
  - ./secret-generator.yaml