apiVersion: v1
data:
    key: ENC[AES256_GCM,data:dTOm6eYqcOGU2kchfsDBCD1Yl/WVzOcLyDR/ineZnQdfpFcClDtlQUtUikSBhhHrTbr3yWrMXVm6pIyq3zEQ/FYMNEaqbDQHm9jJEULIu/SPijxzhcAbVut7r3ATJ8GeelqdBmxdCmIppqPq9wSjj9vX8XpgHQy0jvPGiLshAZ730Br95d25Y5pLzLVTFdxMMG02bfAKN2hmNwNS8ujrI8NZpSPsz9ghyay5pxA+58ATZuPt6vtQSE7VdM8wkKfVZ1iyoB8sYqHTLjDSOc1ZTTtBky8HBXNuz3Fz60Vc84hhNjOMrIz+E2JV6l33TYZTGiEveJm5m+0K81l2M+p40c7mYWrnw4Cbep4wSec+u4lpUnSkJTdSviaqM35M1YHhP4aZzg==,iv:KuS6g7wqpjiWk0MyApka6yVnh4N4v7X7mJxx5yv2Neo=,tag:byPuCRLUKf29+OVi3XE+Zg==,type:str]
kind: Secret
metadata:
    name: supabase-key
type: Opaque
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa0dManpvSFhneFdNU3hl
            cUMzbDFhVUl3YXFqdUc3VFMybVpPMmhwYmhZCjg4cmpxdGRyM1BkQTRiRnFpSzNC
            UVRxdFRRU1BjOWdPck81aExNaUNtSUUKLS0tIGJCV1lJcWQzQjVjdlFlbDB4bmhY
            K2hkRWhmeTlxTmtDWStnTExlMkNiVzQKCLDcWwd3QO2QEmnysHwk3QjyEOFTw93L
            +LbUOJzQh69FZzgo/akC43Ht2g5lcfGgx2hkV2Hdc0H3Wx0//tqBVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T15:01:53Z"
    mac: ENC[AES256_GCM,data:Ep1I6TxoE/a01wzgLefSLEW+VaCESKwzxAeC94rp8jaQu3VwpEcZc6ohGqryvmToHoSekdUJc/9AEvAHTOHJ27MnLeHkc7s+CexqQ5ejry9zyzfDvI4xry7Khzd40hhqidov/bWM8WWSWOYMSD9HRyqg78A2No6ku/WM2iP/ITk=,iv:J3aXmiqE6rrLyUu2N+ZE3zOizooRoYmno0xW0FKQjAQ=,tag:oQD4KBMXsjCp41iiXowS2g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
