apiVersion: v1
data:
    token: ENC[AES256_GCM,data:QfC2BcbjGioxD0XVbx/MtGPi7Fry3zuQQgf6HyZ4zSBYBNKYjJnwPGINIoFWutIk721dL56Ty4M=,iv:YHiA4jx9cuJH9I7q97TM39XgkdKgVvjXCd4jxsifzVs=,tag:mwFgkstw8umTcokiS/Zv0w==,type:str]
kind: Secret
metadata:
    name: namedotcom-token
type: Opaque
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZmgrYXRzM0t0Ri84L3po
            RjB0VVZqbm1CV0FHZzdtWTVUUXJVUTVVT2xvClhWODhLWGZCYXd2QWZ5QVZTMHlZ
            c0dFL3Fwb3lUWFp1RDBQbFIzaVpMTkkKLS0tIDdpUWRWc3hCUEIvYU1HMGpiaGN5
            N3A1ZGJRcEdScGxWWW9uVW41cU9TeEUKvMDOV16udJEsMfqAkM915T4KCL6ZNihN
            diT9hFtRO6v7BylJMtOopXxIqvwre4j7pr4mFanjTr4WjMgnL67/xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:10:21Z"
    mac: ENC[AES256_GCM,data:StqPxJFGM4m0NuI54eBI+40Qlkst2zpaA0YPt2L7Egs1ltPZffgBY0TS5DZ0FZBsgDhCsPL4NtBzUjeYeTit1xtJxrg3sS/FsLd7bx6yoTJmxJSBd4F2EL2IRG4d2tConCeEP/RBhJrGDRVnzgn/2Ip9b4mCRVZcGYTkaFYQaYA=,iv:yXwKss4bpCeiy04HL9btjXgnzfcOUqknbx/hU/7AZrs=,tag:NwPcmlta3FpYnPETukw8qA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
