apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: lette-proxy-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./redis-secret.enc.yaml
