apiVersion: v1
data:
    key: ENC[AES256_GCM,data:ICL9j2j/NB+71YEnBJfMDzK8ylY4nWDF4wkE67LoDXERfkxmverSyjGC0xFAY5IBZ5pxvZD48hJCsQdK95cp1WloW9jtFRqcBwd7hqhk1+oZG+mSIrweaDZ6hNfk0vXhF4f9gRsTOezoEzgI4Pvmwp2ezE813oMPaw1zmTk035aw2EvPbMvlu3Uc2JLCunrx9g6CSOIXimysQC1qo1ZW6z3LB3GGJcsaiMBukYiMR3OUu148us7wmcgugjmx6PPRZzA3aT4SnMuIVjJihFnvEo+Y7R0LDIQv7MjOMX3HctNfZlpX73CqU8opqs8leZLbe1qEJuA3Q7OOYjcZaS5J5if97/yt63uyYExO/1WE9s2l9fIxbV1n1uAdigQAz+y9dS4d8A==,iv:C5PQDqACz5ElsUCXblkmd70RDp6M/TA/nMajduEjOZk=,tag:/ydeQ0oInSu7X+x77q7CEg==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-01-30T13:52:36Z"
    name: supabase-key
    namespace: lette-proxy
    resourceVersion: "538620"
    uid: cea7a2b4-6934-4e52-9b1a-a5daa148f242
type: Opaque
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RklhZXVSdXJ6RXhmRTR5
            bDlFbkl6N25LYWxWZS8wZ0lxSndoY0kxZEhvCmtDS0FUMzE0dG9uWXFtRnNtUys4
            OERNR1Q3WFo4UmJ2Mm1FS2lobGNMaU0KLS0tIDN0RzM2TVJ1ai9jRnMxR2wrbXky
            UysvS09Wc3E3Y0paSG45dU9ESmhlNGcKmVPuJto60Z+dz5OY4GDCoxYAPH8dCQO1
            TLo4jXyR5bAcm5YpNU0eCNgfy3VJ/vbkn8WVT2o8JVGMkhwaty1iYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T13:53:18Z"
    mac: ENC[AES256_GCM,data:fIk4tltUf9Hs+aYBBw6vYnoFIh0xnFjU/+HCe4+DPmVrjgoMOuK6EY85M0bTgJePG3F0k0zVJxh/cmEovIDMamrlp4Hpk4U4plf9WGw/H1fDbiFfbzs7p0EF3OH8DnPKemZf+DYgXyfBxuZvDHf6EwaoCdaWCKrtiQRcHzglXbs=,iv:tDUAeJacDpEWIeVtQygKN1k1VP5aN4raJ5fNxYS03QM=,tag:VA6urorZ6q+F3vRHyEfJuw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
