apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/standard-install.yaml
patches:
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingAdmissionPolicy
    name: safe-upgrades.gateway.networking.k8s.io
  patch: |-
    $patch: delete
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingAdmissionPolicy
    metadata:
      name: safe-upgrades.gateway.networking.k8s.io
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingAdmissionPolicyBinding
    name: safe-upgrades.gateway.networking.k8s.io
  patch: |-
    $patch: delete
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingAdmissionPolicyBinding
    metadata:
      name: safe-upgrades.gateway.networking.k8s.io
