apiVersion: v1
data:
    password: ENC[AES256_GCM,data:H7t77bfK1BXgDjfKz2Tg2BbEdB2ku8M6ALEvpMS5Zik=,iv:Vrove2Rc32bejmK8TCEJLGofXG7C4q65SJqqe15no3U=,tag:lAz5laXMeJO6Hl5CYbzJEg==,type:str]
kind: Secret
metadata:
    name: db-password
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Mk14cEtMdE9OZ0tMcEoz
            MHZ0MjlENUgxWVhZRVVkT3hYUzFGcWhSVVZZCkFwMFZEMXpzQVVSeS8yb1BudXQv
            d01qTlFIOXFmR3ZWTUFHWkdaZUtvZGsKLS0tIHpKaVhTQk5LWXN1azZoak5KaUgx
            TlJ6anpiclZ4U3gycU1sRXR6R2p2TncKpDqgK5lL+0Qi/UBlTUD5QX1xBMMSuSgg
            2uSm25v9UrwYeTLizlUQ5pjY3p0DZ2uPdiDm2z60OtHLv66BCJhHOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T15:35:40Z"
    mac: ENC[AES256_GCM,data:nL7QxEt5zpTMyDB07MgeBTeB4ULTO3rib/g5+GEPd5/sIgwpnAv5m9DfjqXXdfsKVZ9n2Kdz0I70FwMp3KUm1JazotcFdwb27p/AcT6Do+zRsb6FDmYvNTfpdS+I2SsshS3odqeC/dVI2EW+HytuK+eEL1JXzKkuQTXGJhxqAXU=,iv:14GxCF+uFHnYRGoX7x5EIRp++iiA88V+a/YG3iNTeEc=,tag:PGqJtzKbChgzGHolcn7ZKA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
