---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lette
spec:
  secretName: cert-lette
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-namecom
  dnsNames:
    - lette.io
    - www.lette.io
    - backend.lette.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oana-asdf
spec:
  secretName: cert-oana-asdf
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-namecom
  dnsNames:
    - oana.asdf.ooo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matomo-asdf
spec:
  secretName: cert-matomo-asdf
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-namecom
  dnsNames:
    - matomo.asdf.ooo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kimai-asdf
spec:
  secretName: cert-kimai-asdf
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-namecom
  dnsNames:
    - kimai.asdf.ooo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pkl
spec:
  secretName: cert-pkl
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-namecom
  dnsNames:
    - parkourluzern.ch
    - www.parkourluzern.ch
