apiVersion: v1
kind: Secret
metadata:
    name: courselit
type: Opaque
stringData:
    auth-secret: ENC[AES256_GCM,data:1XK6OW97XZUILv98qqyKgJPof/V3og2qLgnHQaVqIXHgR3GNgyPwDOhSssl+2dZsLwL3ZHS8w9JuYwg4XEgKnQ==,iv:/S0mT4UjUYXz5eOiW6UD7mvc6cMZcADs06yEVNwEii8=,tag:KhugeN3q0ABKQBy/42GK6Q==,type:str]
    super-admin-email: ENC[AES256_GCM,data:hCszSMLUk8eZUwnKQkrj,iv:wTcoTVMV096ZF8DHmcjwSKOc1Ujsea7+0PAFsELm7po=,tag:TPPJ9/IaFowGsOpeHOssvA==,type:str]
    email-user: ENC[AES256_GCM,data:G1b+QgXtsWdodq8YyOOg,iv:EUK1WWgr/BMQqx6qvHuC1LNqlGiNAnpqw9/vsnpQmPg=,tag:pD2jpxFeIRyE5MCHu1xX9Q==,type:str]
    email-pass: ENC[AES256_GCM,data:B53d24tafOH+FoxboV88jiOeo9I=,iv:BJYWO5C3D0PX24tDGnymafqp7daJHR3lupdwvLpE+II=,tag:NL2qE5bZq3i2aojGYe+8vA==,type:str]
    email-host: ENC[AES256_GCM,data:9yUVJlANvpUE/E8yjLM5vEu7,iv:R7a1/I06pVrRtFjeNtkwXNzae+IdWt+Dfhv5O8WWZb8=,tag:qFnLnEaUcgKYFrLVhRT52Q==,type:str]
    email-from: ENC[AES256_GCM,data:wRWaoNDuwsjr7y9P5ZSf,iv:nT/SH2cC1joRERxwRWw84TE3LtPyg9m1d/SEusDLrXs=,tag:kKgaXb9w3HW/ridhfD6LuQ==,type:str]
    courselit-jwt-secret: ENC[AES256_GCM,data:vR+ADxD7zkl0jVZhqN9uNxFk3k6XLV0r/c1cTRbZu8F0eMw+l7QKshBFshlX/GGhaDI5wsOEaycjQaMdYZiOIQ==,iv:9XlVvrYZNPgcRW4mg+A6HclzBmHG0z5ZW5ykhk6WAB0=,tag:FDYWRDGB0LM/01xQ6i09ww==,type:str]
    medialit-apikey: ENC[AES256_GCM,data:nXBHnOKCqbSXqN6Mzj45g/UdomcR,iv:K0w2de5fRoIBMWyM618ODzMQYMUKbcscvwnmgXZk8C8=,tag:7lKpU5CO7x+eRa0tMAB1iQ==,type:str]
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1endmWFFzZG9Ec2FkS21Y
            RzI1VVpzY3MyT3hyWVlqcm5xVkkya3QxVEdRClhCRklxcEpZTHNmUmZlVHc2WHRS
            bzNrWEl4U3BtNGVTa0hEY0djdEFpNFEKLS0tIHdOVnRrbWRYUWFZSjlpTURHTWpH
            Q2NUSE9hejNlazZJTXpnQjZmc0dzVjQKsqwmshW7aaj1lonAvY9itu7qlkBcWl2A
            cbfvQmBVmQZ+o1fr6iHlG6cADdNlB0Mb6s4yBrcIG7YOIK4Tj6xIJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-10T13:54:42Z"
    mac: ENC[AES256_GCM,data:LHaB3rIX4pU9TTwxLKIIOq7+sMCsoAEuJdR7hIaWkQtwTnewZ2UJvRWeeFGbMs1m1f70tb6qOVtjtuvdVtsyfv7YssnVJ6R4KgOnwQWgyjG5dfdAThgGeHyQVsyeP7Vjqlau38jOBILdJqXocwufJm0cdUtIBDiPu/nRHVHLd64=,iv:Q3R1UAf9Nx0BHVjCVVKi9TgXdPZQutP1i+eP4b13Xak=,tag:W2UO91L2EkrrJZi4c0wnqQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
