apiVersion: v1
kind: Secret
metadata:
    name: courselit
type: Opaque
stringData:
    auth-secret: ENC[AES256_GCM,data:ytc/zTeovX50SuG06P8OsFQJ8i/4t0JJaedSvpT8ohK0M3wAovK0VBQJMOsI23klhFaLNKOny9ICJ+BXyCbA4w==,iv:GELTPHWH9fSsEPRuLPhKPhtuBl+r3CoZSXe+e5lFGwY=,tag:zBOvH9JVuxMsOT+rALIdqA==,type:str]
    super-admin-email: ENC[AES256_GCM,data:akYK8IcLNvWXLM2w27nY,iv:CdG9lC33LRLzTzSiVhXxioEHKYvBs6hgiskVJ50Ycxs=,tag:sNfJg7GqT1+FjzdOrtrVcA==,type:str]
    email-user: ENC[AES256_GCM,data:GFxevV9CgFUvovCyYj18,iv:dI7nrOpnwTmplm7wPlAyAufTbAX4lfFFt2/Ymi+Os+I=,tag:tTCe/rC+xaUKouft9BT/KA==,type:str]
    email-pass: ENC[AES256_GCM,data:d41jq1fQp1Psx3rMyDm6CFs5eBk=,iv:h8+16r07u6p7p+EFk5tdbQywsn8NibC9bU3YXq4h5nU=,tag:mD/6d5koLwCFUSz34wUoLA==,type:str]
    email-host: ENC[AES256_GCM,data:0juEyBfJzHGI7saWQIwc1CoW,iv:4V9ygVeZUnUnf6WVw/zJ7rc3zUEP0TNNhuqhaU4C2PY=,tag:6jQR3sPvdnlMMOJfmLiEVA==,type:str]
    email-from: ENC[AES256_GCM,data:9GzOpTpZOnA3Qn5QjHPQ,iv:4o56xWOP6BKYG6QjBoLc5jgixzCPSd0avA1m7h6XsbU=,tag:ve34OFgTUqsfxNte2vUwfg==,type:str]
    courselit-jwt-secret: ENC[AES256_GCM,data:8Wt80gbVi4YbHDbf6SSYrOL4wtllGMp4TZ3wnNs8Kx4yerX8HWoAsFMnEX2hTayZKw6F9XR9RT31hTXdRizQAQ==,iv:lLu+kTlm2AdL8qQ5zrtFNg39e3/Ay/NgOvKHNuRTf0M=,tag:xcyl2bnxftiBwSnhIHzeUA==,type:str]
    medialit-apikey: ENC[AES256_GCM,data:xdKKXNnvf5LRLQ==,iv:67CevIkgWQysfV9NEpR41kVDOYkasWUSKWbmijUBvSA=,tag:hVb0QE/XDeyAouaNEJgHPQ==,type:str]
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRejF6UjE3bkNwL0JkYmY3
            ZHZwWldvKzZXT1lrZG1xK29Na253S2g4N1ZRCkEwVTBUOStqNWpUWEh6K09BNndF
            am5aU1MxSGRielkzdTJYV3d0Z3QydEEKLS0tIGYxU1psckJyYlh5cmkxU053Ky85
            YXJxc1NYM2JCYUl1RnJFb3ZPMFdmSjgKf0JBAwol8Of2xHhe8Tv57A21lYQPYs1t
            Ua0r0uz3eCXCH4yZQ4SdCBEAIPtkdfX/6zlmOU8PJpAU3h7Ga3nYbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T19:35:27Z"
    mac: ENC[AES256_GCM,data:+EMWkiS9qOlQ0YcEPs6XDlaiZhNMRHDlJlwmK17sFlMyytxh45UI1aVWXF3dP/ozQFZii1734dMITUi2V7gWf39cXPVxlUmok0JV04qn5EJcfnMf8CPyPl5dK93Ulg4hELD6EaCmrg8AbwDgE13xfAVztqu5yxWt3recqQk0Nhc=,iv:255WoQalkUtlEMuBoaepyL/KwQn2upYMprvQkHOZ/oE=,tag:K1JgnXt5tx9BXLZmekTpyQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
