apiVersion: v1
kind: Secret
metadata:
    name: medialit
type: Opaque
stringData:
    cloud-endpoint: ENC[AES256_GCM,data:i8h8qnxymqrqD0Y8qy38N7cHJ+xPtxd7p6XKBrGCq1SjFTc=,iv:uEwivggJXV7E9pWvoX37cT/vCGldoO1N1biZ+bsz01Y=,tag:tnmH1YV7NgMWlUS34q4SHg==,type:str]
    cloud-region: ENC[AES256_GCM,data:K6F5cQ==,iv:WVli4TloveTJKp50BpaHXeMkG7EK3tfM4AkA1w0rQcI=,tag:jxN6RYEo1bxvlPKRj9dnvg==,type:str]
    cloud-key: ENC[AES256_GCM,data:ueUbJ97OXSk/iCHxSOP37gD2Tys=,iv:QtPDX7uA5FETl2tk+fw6Z7oLn3krQiYE8EWjY9B/KTk=,tag:aJUoTWz1S1HlVhAnnA7XYg==,type:str]
    cloud-secret: ENC[AES256_GCM,data:FhZfY3r6vzP/toNPQpWrXNJxk6WVjyRhWpti14Q69luNVZtWpw40iA==,iv:uNt/rvDUl1/qJV73ZZ3Opz6/icXUZ7ND1gOxMwn7chM=,tag:avlJyzcvSSCVC2esxaM0lQ==,type:str]
    cloud-bucket-name: ENC[AES256_GCM,data:jbb5RnQ=,iv:6nV4OzL3bg/eZqfalzVTGhLU6kmsLF0g7Xq6aQ7lnOw=,tag:CQb27R6QSsmX9DGF7WSLig==,type:str]
    cloud-public-bucket-name: ENC[AES256_GCM,data:B71bcPflhHYl4KGH,iv:vYmNuBx6dgpvpRQOhNcr/4VVxWUtbXANM9GQR3oLjmU=,tag:EooCIdwUWWqxhnnQp3il4Q==,type:str]
    cloud-prefix: ENC[AES256_GCM,data:PARrWMrFjNp0kM+3fxH4PIjEOao=,iv:67oWCf+kicLVgaO7bsSiMY660sWnvRDZNhFCVMl6qG8=,tag:qgQO3DZYEO0JMnWkmAIEOA==,type:str]
    cdn-endpoint: ENC[AES256_GCM,data:yAuKhx84iCf5L/wEeKj2JbYSeWyzELum2Zf1wSIqVFytYWOLkjwQ+7QSU6EH/5aP,iv:OkSfntD5mud66I9I2gWXyte9vufFUWqalNnR9rfkRB8=,tag:2UrLX8HyRJvUjJXcY62uEA==,type:str]
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdGplZE8vVmhiTjM3VXI5
            d2dPZFYzSDNEOFZHTVR4RDNhUTdoM082WkFjCnA3bE9haGZ1d2tBT3NjY0FFMkpq
            NXFkOFF3MytCSHpwKzVNUGtjeUtnSHcKLS0tIEVOenhtVXRzRnVrRnJVVnBwOWRE
            anJlRlJ0VjRPdHVTQzRPWGg1UmNHSFUK5fYWisakCgKsXJQZgP9rYouKhd0/eY64
            zITO0n68w+Cwx0i9CFv8sybuJgwB/O7RvTO4/3yclMmbxtDueX5dGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T19:38:45Z"
    mac: ENC[AES256_GCM,data:1E6WKY5Wwz9Xn1QuDCu6U6ZaDZV2cPms7v9Ft46grB8P6HnmPERKpmKrVJFM+8qx2umA055UYeS1GHA6lCt/lrxQDygcdCPxlYmPhMSiOp4zJ7u6mY8KyDBKQgnRyUlN6z4Vz1mey5+laxhkZRrhmk05BxmBbQ6GV/ewY8fyifI=,iv:VFD+XrEyi44RhJgXUg7elzNeHBHtNy5hyiouUJ+oVsw=,tag:GcnAc5bHc4zZsRBiMsysrA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
