apiVersion: v1
kind: Secret
metadata:
    name: medialit
type: Opaque
stringData:
    cloud-endpoint: ENC[AES256_GCM,data:UZx/NMZvMMcPbc/jggKcMEf9ob0b2fbmc7k+,iv:13lc3VoHU/Nd0aR6ofPTpygnowBBIOztLveoBT1xQkE=,tag:l3Fq/sI0OXuPkJT1OCNHeQ==,type:str]
    cloud-region: ENC[AES256_GCM,data:KMLz+g==,iv:sqScyGRBKv6EXDDIzsGVGYMJTrlJdQHZuEeF4YhuzOE=,tag:bj1ynMWJ0G4N8wNjO8cl5A==,type:str]
    cloud-key: ENC[AES256_GCM,data:oK+95bVXai4E+WpVgz22DVJ8rzU=,iv:fx2i+51X1Zs/WfEsqhh2fWV4F493p/I/M2W/E4Tw7JA=,tag:eBiM/szgyj9o57eRboWB0g==,type:str]
    cloud-secret: ENC[AES256_GCM,data:FIkivLaukqksLmzkU2TR4vCDgWu67UOVTZZuau3ctb/7uvjB6Jb30w==,iv:iEs7DOaeeAXzgB7fr/Nnyyk/ulw5l5mt19g8qL5/R44=,tag:oD7nnew8DrdVMBiAiy57HQ==,type:str]
    cloud-bucket-name: ENC[AES256_GCM,data:dN141UH5AHbbuthi,iv:FmgV1RShfxRtqdkMY66nJu/gdKlyHUlcYO5lbsXNWqE=,tag:4Epx0Yt+BhvZvIAnPrAdeg==,type:str]
    cloud-prefix: ENC[AES256_GCM,data:YNdxc2ZRai1XoPOmvZ6NT2AqO6g=,iv:QUoI3QooUD9YV3AoXCZ56fjriPEsOl/QAJjCFVaOvPA=,tag:2jAAWEywhrNXT7dGOMAt3g==,type:str]
    cdn-endpoint: ENC[AES256_GCM,data:I9rTCaX5o3QW+1GkJCNWWW2ZIF6oCm5DNLhz3bcbsdJtNRUP/w5Nx33IIbPKH5YL,iv:/+2eLFTpiV/mhuNm4VrHokTsyXWUkSypYlGXp7vUKUc=,tag:WfFb4rSodftWlnWhMSm9Jw==,type:str]
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ2lPdW03ZTN5WVM4QkRC
            ZjVweGkvQ1Z2OW0vTDlQdkNXZ3Jha1NvcXpvCnJWWDZFc3ZXTm9FK1ZrREcrSVBp
            NDN6WXVnMm5HL2hDWGs1YUJwQ3p0encKLS0tIGFjWjgrUldaQnBYZ2FZWWFZWnh4
            RXdIV3FhRURWT0dGdXNLYVlWYm9nU2cKxGGjQrLhJ2dV0FkE6jJUadjCyEPHsQZg
            MezYI3E11uqnESjPaQdA+D2radguIUvcX1UyMDfstTu0amfLKRblMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T19:49:57Z"
    mac: ENC[AES256_GCM,data:XLBmh6/j0wIRRhX+LeJZ5RwVvh5nXslMNysoo6DZBy+fe2zTrcgNaqtiHO9UvRby4ZRqAKMrgBiqCp/iFIlQPyBeKiClh+wGmgdGzdF7+Zgp4zx3DDkpPppyGBTC1P7og6ax9kkLFSViyLoJgB845b8ej1UdwgxJryktI0dl+8U=,iv:HgWhuQzgt0e1ayls0WoJNrohnOyoQMQ86EHL/uZtHJ0=,tag:mFYUJafX4EVy9vAtEE0L/g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
