apiVersion: v1
kind: Secret
metadata:
    name: medialit
type: Opaque
stringData:
    cloud-endpoint: ENC[AES256_GCM,data:uXCnVkWkP5e9FeNdmJLE4dWWkZY4qI2j1wHxXxabcLHgL14=,iv:a4EC82aedyI5bjgfWJ/n+xa9tibrLz04bxFsVgMTTzY=,tag:bpsDfoFB1bNIwsD/r8OCpw==,type:str]
    cloud-region: ENC[AES256_GCM,data:040UhA==,iv:BRSZmH4EBPTfh4wr59LFjjQKK0xL3TGuymTkac3arH0=,tag:fSIbq7zDfH/kpJkoD6Tk0g==,type:str]
    cloud-key: ENC[AES256_GCM,data:eliB5K5tMzLpRbmlqx7uuJQxqwg=,iv:xLz6DHTEt+k8Sc91iFPEd5HSL1n02CzrBk8NNJuYA30=,tag:ye31A1h4QaYu2DqCX4aVmQ==,type:str]
    cloud-secret: ENC[AES256_GCM,data:07MxTsICtpxwUJQ4NzEm5qBFkJNWCkcYPNs4WPiF7ZPXV3FK7r3tvg==,iv:8PrLI0Kqekf6kWw4mglKZH8MFnDwd6CmCTYZ1KQqNWo=,tag:3vIVbh7wM+WJ3IfQetWZ0Q==,type:str]
    cloud-bucket-name: ENC[AES256_GCM,data:VmKcKc0=,iv:LldXhCXY4Mj2nQOGRf8G07EZVIR8u/Tw6SK1HxZz8zM=,tag:BL7vI0uJ1G1l+lYZfd0cdw==,type:str]
    cloud-public-bucket-name: ENC[AES256_GCM,data:25zp1mSsFgNYZ6x6,iv:JG/qfH69MYBsd4rVI1vwnYqXPiVjfTGsLL77W40kDEQ=,tag:07e8vL7E8YBSbud+lxFy3w==,type:str]
    cloud-prefix: ENC[AES256_GCM,data:ar+6Av1v6JkJ0lGxWXTTVu8+VLo=,iv:LgIPwbVwhqaVaWE2bAhHMf4RfRgaPaLe7wB06kFEvYk=,tag:x5f1ykx3EhQBQ01nIUWpPg==,type:str]
    cdn-endpoint: ENC[AES256_GCM,data:+wvFmU5RJVPPeBqPcvxqgdknLpgwNEfeFGX443Fz6tyWB8MSFaOj7Mn156dl8dz0,iv:Ra3VXC9ofjVNlZ42JdV9IMVnIy/BL//juLEYpfxsGuk=,tag:qJQ6jzMmsxyLDOS6Gu7rGw==,type:str]
    cloud-endpoint-public: ENC[AES256_GCM,data:oNLcKs8YXyVDnxZNGnXYV6CshBlb8GhtGU5S4idEI+ACuf0=,iv:THYjaQ62s+blxmZaBXryzxL8+vdVzsp5bM+USelraSY=,tag:5f6eEBq9iP1MW9IhdnqDPg==,type:str]
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRFpXTjBvYm5aYXZDTWFu
            c0toNWd5TUVjd2FwMHNHNWJLRGkwOEV5UXg4Ck5JRnA2clkzOGN4dGlqeEZPRWps
            QnJ3U1hzWmsyWS9EcmEvQ2trMFAwbG8KLS0tIDFaM0RrY01zM0NSYWwwd0E3UjV2
            aW1zTnpDTkQzMGZRK1NsMFhzZHI4UG8KPnWI+/Si3/1ofQrhNVNaKvkIUrs0MRGr
            ccIBz04GZTYfvu3FrFlf1vhLfnVjzpfnRg9GIGhzGlwYpD4/uF931w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T19:25:33Z"
    mac: ENC[AES256_GCM,data:ELcY3eyFmHhozn99GgcFzrryq264/Rzmlk548hKXrtqqC1TSHmUIZ3QVhWF+8CeYds86jJ9p6e5+avxFwiQ3hZ43JXGTDolqLon/ZFiNsTCMh1wtNgeDK5JxoYEsu/2fbbXHxGYRebM8P+/ogNdzKIsoqpEdMZ/7QZRcQPx02bw=,iv:N50d54fiCPQhni8TfQhR48nQBKDpiQ3GLr46TDUGhJo=,tag:SkGOQqhcojjroDtfgzh+6Q==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
