apiVersion: v1
kind: Secret
metadata:
    name: mongodb
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:tnN9PJ0CRFoCjTpHDRWycYNykfBACDu0tJide7u+Kk0yOG+YcrIpxa4V0gI2B5nK,iv:L2KM+OUqXtnoQqpdoatkTAUnKyYdwC4wh6p23gr6i4U=,tag:nL0IqJJFPcdrmHjRBlC5pg==,type:str]
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWlVjdkx4WDRoMVdyU0NH
            MGRtdTZkcTZGZ0Rkdk5pdkdFbFFFWk5ydXhRCnpSQncvdkxSS1BHdW9FWXliODR0
            VFhWNDhud2Q4SUxZNlVFVUtSZ1ZqcjQKLS0tIFNGbTk5bVExeTVqNXhhaUtMQk5x
            elFnbFRUdHNEZFVCdWZia0xWb2xEQkEKv5dxLoJZxGajk09aL81vxlaAsqa3IOXK
            fCtvH/UPdQI6DDgy4HqgQGrCXvu53t1sCIooSF8IpRPou7T2tuaoIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T19:36:10Z"
    mac: ENC[AES256_GCM,data:+HO/EGxJyXqp5cR+o7E7wTyxQT/aSceTsAWaRoeHl/FGJEHISbFgK7+GLxWnEjqRnHKzohltqc8bFRVV4EBCrYLOVgiGKbtyYmg5dPXj6aBpI6GeE17Gh8CBbvxllmtLGIblvmYM5WbA+XsevOaRggzc6GKL8vGZP8t64M8+3Sk=,iv:LCo39dMIhGTXKKKa8edZ8waBAWXNq/vkhE1lo6tmJ00=,tag:saVmUeT7yC35pgcSPs3uKQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
