apiVersion: v1
kind: Secret
metadata:
    name: ga4
type: Opaque
stringData:
    api-secret: ENC[AES256_GCM,data:K3swX/Xh7+mPP5jtxglAq6o9NlsqJQ==,iv:BgxaopM8vtHCZtYDxE8zSPHWJEnvvBLbMLZBaRwYDtw=,tag:Z/7Z8eXT6+UPAG3feCuEQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTzRjMUUrRk9SUEJPMVJC
            OUdVTU5iZ2pYbm9BOGJoR0NIaVk4Wk0yam4wCkRpVksvZ0ZSN1F0SFFrdG80S0dk
            VGNvQkpDcDVsc0tCLzJ4eit5SStsMjgKLS0tIGVsY3ZXeERZbmh0QmU3cno0S1J5
            enUzUjNlQ0NubFl2MlQyQlBHckN2UncKX3DSsJ3kRX4mDbiV5KxhMCRRAlSNj6Ry
            iWVWgPB8q6Op7xeyGmNJ5T6bemaW1IdgMRuq2DOwvnJ5Oq0uSA7Tyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
    lastmodified: "2026-07-31T07:43:19Z"
    mac: ENC[AES256_GCM,data:cj40LXBLzU2GkJeNe2cUlnKIMyD6iTqV61sO9Z0HsdbDlBYNQ6CdKj9jj7+P//0NMQrXGtVTpC1ExWNFHK/k7Pv96lG2UMPTxKfLZlJah7wlk0BULRE2meViQQT1hLMJ1p1HoD3hEqep8ncw4m7BJSEZFRR1tl/56zeiDQcvS3I=,iv:JB9x2YQb7MUi5jpU4sLsFQhMarHykWcxg5xE08gmNTc=,tag:CRDAO5upRa+AjXEon2rFuw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.13.1
