apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:2mX39EC+0BS94fU6XTUmDHlt4RtoRMbduwZVdw==,iv:HIyz7CWBV1rAMjhkiXWceSmHmPggV1uGL5u8YPToe6g=,tag:jhU7gh1tjO209wzQgdbDBg==,type:str]
    replication-url: ENC[AES256_GCM,data:yCzyUStNsCKRB0q9cu/NdObUVdSDF74N5roucyleJAT3Mfc0vuD1OIoNm6KFvDfeIZ+k6fxKKbbClTxQerE+npBQ/RzmwVC9vuGV99D3KnLZmD4Z,iv:EXJmuzMAft912N7M2RpAbaQyQeIWm0uUVsAzprDwT6w=,tag:9NE/7Q/V2lnCBFTeU6b+CQ==,type:str]
    secret-key-id: ENC[AES256_GCM,data:8YWJo4TA+sCPN0FgCRFMKPITSZ1SPUZVUypuzlOQFKeFage8c+3zyulfV1DLjKwu/PEtP6t0z74=,iv:c+FWcAJZg1vblq1Aj064k2+8Hii6dtntq4IvLWUJFuE=,tag:5tMqezAYtqogxdhxYPyFNQ==,type:str]
kind: Secret
metadata:
    name: litestream
type: Opaque
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aTNMdlRzdzhhNm9FQ0VP
            dnpuZW5abHF3cmU0SUVyK01MR1lUekFYcURJCndydGZFSXc4QW04cUlYSTdtOU9k
            NmlIQU9QTVhEWXFaNkpOQUFqWkpjNncKLS0tIHZTYzFvb0VDNE4yQVZFTWgydEhI
            UWVuVllVRDU0dzdtYi93TllNOENIbHMK2pFeXtXpgekx0tcw94CYQqX2J4lt6qTA
            WBX8ik0r8TsbAdgn6E1txnH2X1dny2jaDB+Btarnx71PNTzasktzFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T11:18:32Z"
    mac: ENC[AES256_GCM,data:rDq6OowJ67Rbjw0lrCMmrHz9Z+QdX4nvKotPuQl62jMpt7u7z/AxIsU3htOcMs2BsPI5DmL9fJAz4idKGSqK4ysKbzG/zj/tkCmuKjE1xrB2Mn6ubfUj1kzmyW9MUndTv87zwe0IUhWvUUwWQVfmtg4/MjSuAG7fo2SqqpMw5YE=,iv:igeCziOb3ye/Au7AhTrkkopAGrUq1HEUyo8OEm2bt2Q=,tag:3bBUdwZx8YcUs8acl2C/Rg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
