apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:eJcpLwnsTMnohGQQ3+qLCcSnWoBhjGEngYF5pw==,iv:rYigS0/yn6stvs8EBdgdyMqKvoyPs3RUhp0OF38gyv4=,tag:Y5lptEn/9I10G5cOtIuzAg==,type:str]
    replication-url: ENC[AES256_GCM,data:64BT5R8z+CcLUukxrg2/qgUNh+xgrX8gMNaaCgGWB59el9K7uNsRv1Ll/fU6HtS3baJCSoPUd29uYesldj3MuN9I4pI4XpX6DqgNbNkXyE4=,iv:XTX4vpTAXpjSUxIvHjGuGnQYLE2IG6eHU9LDkifvK5A=,tag:r3lFRw+LGdcDvrsvlVk8+w==,type:str]
    secret-key-id: ENC[AES256_GCM,data:fjuHg8waqAdjuckcrH1ULxV59dVOAeGGsCS3D9c1WcPlcOdZanZVH3jHZq/zAYO1LXkVN5tRrIc=,iv:6oARMRCnRqr5jnet3XencVzy0/aVl0eqVd8I+ap0vAY=,tag:OePq/DVsG9bjjb6VT/eHHA==,type:str]
kind: Secret
metadata:
    name: litestream
type: Opaque
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURjcweVloUXdTM1dmTnBO
            eGdONmNpcGZGclFOU1V2M08xMUlqNml3Z0F3CmVnTDgyc0FsbTJIckJSVldhT0dU
            UDFyTUllSEg4STIvUjN6OWRGZ1pYeGsKLS0tIHp0MlExeXZHZk5yYkJCcmJzSVhO
            ZER3dG5nZGVEYnF0THljY1BmaTRTUG8KArzgVJiBIYl06BRjXy2pjHoqt/MuI2LW
            rts0UBNhm12whTve3IcP6VszcfiITPNicG/vAkYqZ0V/6HuD7mbMgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:25:37Z"
    mac: ENC[AES256_GCM,data:N/oLjpoAUbkPp+0Za7XZvr0LKEdvv/2c4nVo52+b4r3FTu2xg4iAaZFdh6nO1nHLHz2GW7pL2JO12hoGioVzfAMIbdIr42WRvvWwSS2xvfWUVbIeGEY3S2lx8yYGbbMIhsgUQu84nPJG8hGoThFvAt7FS29hrvfwTnjUl1ao5H0=,iv:Q82XVdLRquw6LQ7esu8Wsx7jKejwjLvF1empAGipMHE=,tag:AHyyIKR71pKY4UUzvUM8oA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
