apiVersion: v1
kind: Secret
metadata:
    name: microsoft-tenant-lookup
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:yC9rljrvTRMHB61YQF4mZ6SUYNlyWZDqyorRKvzuWjQ2AT00,iv:0GQUBQKnOTljkyoT7fQqCh3Qa5p/ROeyVbhYVVqWGOk=,tag:nXJW4nu6BaqSWIbItiNOcw==,type:str]
    client-secret: ENC[AES256_GCM,data:uG9ztozj0V8iNe0l8r7FsJqnOutFRsTtBy4R0jZU6mUc9SxbDoCB9Q==,iv:4wFIGBP/vepwog2JStzfuuJxgeh6riw3BuEui7X9GeQ=,tag:30ZQUNYfXa5PFhwQxZ87qQ==,type:str]
    tenant-id: ENC[AES256_GCM,data:YioWcnwWJPaD80RbF7hzmricMrcY1Bz7hrkphu4liIYytzvQ,iv:q2YWM6b/yPQbd4dk32XDu6HDOZTcOGc9BOMeLVFR+/4=,tag:jrUvFCctMCRUqx8U33O0ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQyttejhtRzkyVDBva3V3
            dGhwMlM0aWlUSThSOTNlWk1jMG42UHRSQUJBCmxCQ1Bid2cxTUlYNWNLZmtXRFNs
            RjN4d2h3Ym05MTk0Z3RnVFZoUkc0aDgKLS0tIGJGaTgvL2NvdmRMaStmcE43WHow
            T0c0RUlQVXdxcERub2VjcU95bFFieGMKx2fPvGS4arr9+t7aieO0xOwNB86lu2Wj
            QB1emF7oYoL9nSBpfvLXpzj5B1XLl/UiijcfMhY8D1n9lVu2NBRdYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
    lastmodified: "2026-07-19T22:27:08Z"
    mac: ENC[AES256_GCM,data:LGqvJZ8po9b7Cyb3ThTsj0MQQRwu4vF8XYoGZFsjE8W18LPXAL+RUAiPIYEHA9muSGg/7a6vY34iwcqQel2Uma3G4pdx3YAAQhdpcfsS/HEvQt5UxHB7DoMxsJ94PuwuRjINCBXwGsS14+c5olVqzBUas5JfCwwdr111WPldft8=,iv:HOGVGKgPsk9j8sT0giwuTK5dBrB5H+Evx59QGvt/WAw=,tag:7hmKhY5DccMpE+s+Zm99Xg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.13.1
