apiVersion: v1
kind: Secret
metadata:
    name: microsoft-tenant-lookup
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:kD341mYrMpNrJWYd4a8Ou7BECvesBCLUnbM7378FyINI/ZGq,iv:qdrwvtbcO9Zsfl8eTqZQeLhm9P3V2/G9CnS0PTcKmWs=,tag:pxx+RrwOfr1YgAmxlF6F6g==,type:str]
    client-secret: ENC[AES256_GCM,data:ObZtyxG6Hqzs4w9WVaon/PZ0uiDyP2kqU+Tb8GX23eywhuCkQdnDPw==,iv:97gcLyxreRX1DzwpTvJOBg3yW0pnGEuYNSx+hn/7ECI=,tag:6JOAJ2OOihVfP0PwbI0vhw==,type:str]
    tenant-id: ENC[AES256_GCM,data:I1O8KbqmefGV5fJjlkV6U5L/M5gF9Rb0cY60+sZ01yUg4wcZ,iv:8cc0pDhyY3wT75veFAYcgi+p7PZ3YI+luGtN6crpx4U=,tag:ZFyp9K+NcwQbziEvoR1wTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzQza3Awa0lxeUxIaUlW
            S0RTSERTell6NGlpQ3AyM1E1dDZQL2NXRVg0ClB3WkU0RWFZQXQwWlNWR0JyQzFv
            Q1lja0NqRUpJQXF4OGFkcUx3VTdMdW8KLS0tIDZhVXFyeUJ4Q2l3eHNPWWpmV29u
            VDVwRWF0L1ExWHV2b2FtOVNGSC8rNHcKWbCzE++fr3T4gUhNqzrYyiyOYlopmpty
            Q8FESYI74ut1B0/uhxr9h6OMTjkQRVCVcsXejf1FE88aGfMZB9EW7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
    lastmodified: "2026-07-19T22:31:07Z"
    mac: ENC[AES256_GCM,data:3i99Y4fRAc4q/Pfns8dhnkOOuCJYz+zEg+Jg+//K0U9zlm/Z1aBFgzrKA/MvX5rVNFZGdxhQgAkPmTsjoPdfv0F7XIaFjywoHA6JrQUlItsStuYRje+7I5p4oXyzhQ+cxMC+/dXF62Qb5H3ufc7ZyBHNNIroELd/lbS5WBfUg78=,iv:AZmt+eLSPskdNaT0OLQW0+FKJB5Q8FK/vkiHLqjf3h0=,tag:MsPlTtK2WHQk/MoaYgoEeg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.13.1
