apiVersion: v1
kind: Secret
metadata:
    name: microsoft-tenant-lookup
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:LEl+mTva426hgH8gpGwRT/63AZD08s+SLkF9DoFKyeBApldTPqfZhA1RKklNZO+5,iv:krvmX40d3jTCODx3AldCluABeiE2xS1Z+kDU7l88+Fs=,tag:OwiSnXq7q5HU64ODqHKoXQ==,type:str]
    client-secret: ENC[AES256_GCM,data:SdtNoQ/pezJZDLF6+IcNlUEzT7Q4BxfZowu6cJEkX63aszdOj2GLu0BKcUlb4v3ZHNozLO6Pwt8=,iv:MYY9609ATCwMfonHyTUpMaax6nrfM5WXzoMBzOoJiH4=,tag:ATpPYHgHpvjj+0idwuMgBg==,type:str]
    tenant-id: ENC[AES256_GCM,data:VWxWtr2pWdls2PN3EyNdOMrod5ImYsJDoAn+lRAGR5oSs5MyXogDNcsceHFQTVyS,iv:13N02fBrFbfO84+uJR+7o4khw82NaAep9Z8RUt9NUIk=,tag:rpN1Ma+8yIMM1SBGLv+t9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaU9tWWtsVmlTbWQrdFBh
            cnFZT0IrcHhDc1F6MjMwMHAvTkd0K1ZobzEwCm5pL0NmWm0zUDVHK2pvTzQ2MFcz
            enhpZVJQUk56R3VBRkQvV0JEOEdMVk0KLS0tIGNQc1dOQ1M5UWxRMUxwUU5kNDFx
            dnVocVdlTWQ2U0I3R1IvK3g0NDZrT1kKBTRToV9fb4HlDQgII28v3DXeTzXvhcd6
            KcMw6fd0jMjaAWujcIlewLaCn2jrihaHhbjQY92DTecC+Fl/al5DDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
    lastmodified: "2026-07-19T22:19:19Z"
    mac: ENC[AES256_GCM,data:Z7im+pSKuLH3FyG+SFI3rVflth5lbGdD43wn4s4YcSiYAxdMeCP4TnGs9gM6mNMaZs4a9IsPD65vqMNUZbeFDGzC7WE9wU6AxWFhJOc4/FUmdyY6/laT7qbHzQew1f57WpKXq3Hf4YMKtJ2WCtyEQPsrba8oRu4+w9mA52uHKk4=,iv:fTpgnz+2c5qyn2hgxp+AEHrcbSo1BXh6hlRs4yKaMDs=,tag:YAFFARDOh90ogvN1dheGSg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.13.1
