apiVersion: v1
data:
    public-key: ENC[AES256_GCM,data:ZuR1icJgj/qSgedrMgYTW3pnLSTPvJME4dedfD5ZH9Ay6ss19gDOMV4lSsd0OC/qQpZdavcSkS3FTjRlWttbsJ5pbBW7r8iZByocxwuT5DvgeN6ZPXvs0anzyjux4lTwSufKKp55tkqTgTY1akeGSP+0wYMoQ7laKOKJHDrAxfFZySCgjKVKtoHN3j2ZJqkZ,iv:nMQrJbF8fBzNrtJNwpILWPMfa16oEdwGRm5//gUFtZU=,tag:bWMGEGTwMs/XJA3CCKabvw==,type:str]
    secret-key: ENC[AES256_GCM,data:C5NmIJQBmgkiWSi9LUBJ7B2xu3k3IJY3jdvehzp+v8NIzURUC/MAdFRciC4agArKK6DFpY6FerPDcpmWeNBDs4yQXVT5/zHX+RXAvMSQBq46e2s4RVd4Fd67lC97ucHPMMVo9HhPp8CbUL26BgymTyUY3MXTxLi8HPCAILYjAf6nJo9E/aDQb87bKY1BbGpd,iv:MnFp0FsdlX1FFN81Celk0C6Tl7giDyPI09toU9jMcLU=,tag:fgYorhBgnCGC7KK+QVYwVA==,type:str]
    webhook-secret: ENC[AES256_GCM,data:/xQYbjqmwQkNW98dRvHPF7daRckKB9kEPuYJRI1pqpNnW1KqjhXHx9flnhhcmrBRMGltTA==,iv:JhWhCX/+YDu1XJ5JVOqefkg8nWSPYmO2BNE6w+RNpYc=,tag:sjJA3Wyl9RG38flzLDAOwQ==,type:str]
kind: Secret
metadata:
    name: stripe
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOVlWT3hVczM1L0VIVThQ
            S0xndHlYODZxc2FyaVNFd3B1Q2JtdnJ1dER3CnVDQXlQUmdxTHJ4VE8rVmdtdVJq
            U2lZZXNTTFVpQ2lpbzk5MWd3bE9NRm8KLS0tIGRhSVhWZUxSTGczNXQzVEhTN3F2
            bXY5NmJZb1hMTmtxaEZ5SDJPZTlSa0EKjctmWMzUo1kDsJx3oORKaoE62JbWmwJy
            MEWoS0g1ufkS5M3QFIJVcz1e61vJlwnqAiGKK1DpkeAjmiizxe9kzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
    lastmodified: "2026-07-19T19:50:15Z"
    mac: ENC[AES256_GCM,data:jJ9MhjB/zkxDvSe1b73MNtwGJkNZExlxSO4wb5leWS5sblSLmVYxUmV15P+Zj0s7AEFufmJKlZ3TUFp69nSVeg7skyj+qluyOVcbGye/BniroxtBthWDlbJwfxMsahMs7skcjpw1fL3dEBomUxUyWFndtuvCbdwoZf1T7UElZ8A=,iv:IUQe4lP5pVVdmKuVcFtMT60qxtgNwT+kpMg9d6HHcsA=,tag:jvH6jYs6jV5cFSl8cecxEQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.13.1
