---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoip
  labels:
    app: echoip
    app.kubernetes.io/name: echoip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoip
  template:
    metadata:
      labels:
        app: echoip
    spec:
      containers:
        - name: http-echo
          image: mendhak/http-https-echo:latest
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
