{
 "title": "Disk Pressure Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_name", "query": { "query": "label_values(node_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Disk Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Pod Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ephemeral_storage_pod_usage{node_name=~\"$node_name\"}",
     "legendFormat": "{{pod_name}} - {{node_name}}"
    }
   ]
  },
  {
   "title": "Node FS Free Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{fstype!~'tmpfs|ramfs'} / node_filesystem_size_bytes{fstype!~'tmpfs|ramfs'} *100) * on(instance) group_left(nodename)\r\nnode_uname_info{nodename=~\"$node_name\"}",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Node Percentage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ephemeral_storage_node_percentage{node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}