{{- range $key, $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name | default $key }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ $app.syncWave | default "0" | quote }}
spec:
  project: default

  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ $.Values.global.spec.source.targetRevision }}
    path: ./apps/{{ $app.appFolder | default $app.name | default $key }}
    plugin:
      name: kustomized
      env:
        - name: CONFIG_VERSION
          value: {{ $app.configVersion | quote }}
        - name: HELM_RELEASE_NAME
          value: {{ $app.releaseName | default $app.name | default $key }}
        - name: NAMESPACE
          value: {{ $app.namespace | default $app.name | default $key }}

  destination:
    namespace: {{ $app.namespace | default $app.name | default $key }}
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      {{- if .serverSideApply }}
      - ServerSideApply=true
      {{- end }}

  {{- if .ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml .ignoreDifferences | nindent 4 }}
  {{- end }}

{{- end }}