apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kimai-data
  labels:
    app: kimai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
