apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kimai-db-data
  labels:
    app: kimai-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
