apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai
  labels:
    app: kimai
    app.kubernetes.io/name: kimai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimai
  template:
    metadata:
      labels:
        app: kimai
    spec:
      containers:
        - name: kimai
          image: kimai/kimai2:fpm-alpine-1.10.2-prod
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: APP_ENV
              value: prod
            - name: TRUSTED_HOSTS
              value: localhost,kimai.asdf.ooo
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: DATABASE_URL
              value: mysql://kimai:$(DB_PASSWORD)@mariadb/kimai
