apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: hcloud-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./hcloud-secret.enc.yaml
