apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZWibBRgAeKGh1CRm/UBx7A==,iv:Yv6z60dLFgz0keZexqam1NqzNi7tLB3ofxtvRAM3M8w=,tag:dXP2R+PWgaLo2PgrRuwt6w==,type:str]
kind: Secret
metadata:
    name: db-password
sops:
    age:
        - recipient: age1vvpm73fq42ywkr7jeuewjpk8d9hew9u3dq389dy9r85ugezqgy6qh8zqzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN2dTWnJuU0RDUDZQZXNG
            d3E2eHNnUHc1Vmpja3hHUWhyc3dZeElkYUVvCnAvSFdXblBqYVJTVmd2VUFxV1V2
            M0RzdmFobUtUa0dWSVVTcURxMUhjblkKLS0tIDRlZzFYMUZFQ2FHSUhsTThTU2tV
            SHQzSzZwTlBuSTNhYzBOTDh2dzM1djQKlZSdB+fMqutTD+vzAkvnmViDOCF5x1fE
            rS6DVSlljDWebjjc1qlwy/QinVwcIl3hMcB0kvmUP6UmoRYEsQadYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T16:27:24Z"
    mac: ENC[AES256_GCM,data:fGxWGH1TmJLNu8gKNMCx8kpbG6iipe1dZT6IiZfAKVLwWg8plGjQs+yYa2lxy2zSdKNem1IllBqz6g2bCwMY43N/COOtIZTteuoktxALmScpwwZ90d4Y4xrOwsXVkGyXUcAGo09eV68vGZYkMOMdcgw8oH5ctZShRtfFXvwwYag=,iv:8JYWDEkqVjrb52ejOkp9TPXt0pa0MV+PYAbXSKqBskA=,tag:aYlnHQ6TopcojnWxuPraqw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.11.0
