resources:
  - ./manifests/kimai-db-deployment.yaml
  - ./manifests/kimai-db-service.yaml
  - ./manifests/kimai-db-pvc.yaml
  - ./manifests/kimai-deployment.yaml
  - ./manifests/kimai-service.yaml
  - ./manifests/kimai-pvc.yaml
  - ./manifests/kimai-routes.yaml
  - ./manifests/kimai-nginx-configmap.yaml

generators:
  - ./secret-generator.yaml
