apiVersion: v1
kind: Service
metadata:
  name: tanja-courselit-redis
  labels:
    app: tanja-courselit-redis
    app.kubernetes.io/name: tanja-courselit
spec:
  selector:
    app: tanja-courselit-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
