apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanja-courselit-mongodb
  labels:
    app: tanja-courselit-mongodb
    app.kubernetes.io/name: tanja-courselit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanja-courselit-mongodb
  template:
    metadata:
      labels:
        app: tanja-courselit-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0.31-jammy@sha256:6804f11b7e5beba477c1af913c93ac46b9fb6856105aad23f4d464419e796167
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: root-password
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tanja-courselit-mongodb-data
