
kubeProxyReplacement: "true"

routingMode: native
ipv4NativeRoutingCIDR: 10.0.16.0/20

bpf:
  masquerade: false

ipam:
  mode: kubernetes

k8sServiceHost: 127.0.0.1
k8sServicePort: 7445   # Talos kube-prism

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

loadBalancer:
  acceleration: native

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

  

encryption:
  enabled: false
  type: wireguard

defaultLBServiceIPAM: "lbipam"

nodePort:
  enabled: true

# ---

# Customizing starts here, above are defaults from terraform module

hubble:
  enabled: true

  relay:
    enabled: true

  ui:
    enabled: true

  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http

prometheus:
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

operator:
  replicas: 2 # Actually this is a default from the terraform module
  prometheus:
    serviceMonitor:
      enabled: true

# ingressController:
#   enabled: true
#   default: true
#   loadbalancerMode: shared
#   enableProxyProtocol: true
#   enforceHttps: true
#   defaultSecretNamespace: kube-system
#   defaultSecretName: cilium-default-cert
#   service:
#     externalTrafficPolicy: Local
#     annotations:
#       load-balancer.hetzner.cloud/location: "nbg1"
#       load-balancer.hetzner.cloud/name: "k8s01-lb01"
#       load-balancer.hetzner.cloud/uses-proxyprotocol: "true"

gatewayAPI:
  enabled: true
  xffNumTrustedHops: 1



# ----
#gatewayAPI.enableProxyProtocol: true

# Cilium Envoy is not accepting PROXY protocol on the Gateway listener.

# Your live listener config for gateway/cilium-gateway-k8s01-lb01/listener has these listener filters:

# envoy.filters.listener.tls_inspector
# cilium.bpf_metadata
# It does not have:

# envoy.filters.listener.proxy_protocol
# So the failure is now clear:

# Hetzner LB is sending PROXY, proven by your packet capture.
# Envoy is not configured with the PROXY listener filter, proven by the live config dump.
# Therefore the public HTTPS listener is broken because Envoy is trying to interpret PROXY-prefixed traffic as TLS.
# This is not a Hetzner problem anymore. It is a Cilium Gateway API config-generation/problem path.

# Also important: your gatewayAPI.enableProxyProtocol: true did not take effect for this Gateway listener.

# What this means practically
# The chart value is either:

# not applied to Gateway API listeners the way we expected in your Cilium version, or
# not sufficient on its own, or
# only affects a different path than the Gateway listener you’re using.
